---
title: "EP model"
author: "Catherine Sexton"
date: "2025-04-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,warning=F,message=F}
library(tidyverse)
library(nnet)
```


# Initialize Data
## Input quarter here
```{r}
data <- readRDS("/Users/kelsey/Desktop/Sports Analytics/pbp2014-2024.rds")
data <- data %>% filter(qtr==1)
```


# Simulate Epoch Function
```{r}
simulate_epoch <- function(down, ytg, fp) {
  score <- NA
  team <- 1  # 1 for reference team, -1 for opponent
  drive_count <- 0
  max_drives <- 10 # Set max_drives as 10
  
  while (is.na(score) && drive_count < max_drives) {
    state <- run_drive(down, ytg, fp) # Get state of the game from drive() function
    down <- state[1]
    ytg <- state[2]
    fp <- state[3]
    
    result <- proccess_state(down, ytg, fp, team)
    added_points <- result[1]
    team <- result[2]
    
    
    # If the team scores 
    if (added_points != 0) {
      score <- added_points
    }
    
    drive_count <- drive_count + 1
  }
  
  # If the team doesn't score, set score to 0
  if (is.na(score)) {
    score <- 0
  }
  
  score
}

```

## Helper Epoch Functions

```{r}
# Initialize reference and opponent 
reference <- 1 
opponent <- -1 

# Process_State Function 
## takes in the state, adds points, and switches teams 
proccess_state <- function(down,ytg,fp,team){
  
  score <- 0
  if (fp > 110) {
    score <- score + 3 
  }
  else if (fp > 100 & fp <= 110) {
    score <- score + 7 } 
  
  added_points<-score*team
  
  next_team<-team
  if(added_points>0){
    next_team<-opponent
  }
  else  if(added_points<0){
    next_team<-reference
  }
  
  c(added_points,next_team)
}
```


```{r}
# Modify the drive function to run a sequence of downs instead of simply
# returning the starting location of the next drive. We will pass off managing 
# plays to a new function, which we can call run_play that actually 
# manages the plays. 

run_drive <- function(down, ytg, fp) {
  # Run plays until drive ends
  new_state <- run_play(down, ytg, fp, team = 0)  # Team indicator isn't used in this version of run_play

  # Unpack new state values
  new_down <- new_state[1]
  new_ytg <- new_state[2]
  new_fp <- new_state[3]
  team_possession <- new_state[4]

  # Return updated state to simulate_epoch
  return(c(new_down, new_ytg, new_fp))
}

```



### Helper Drive Functions

```{r}
run_play <- function(D, YTG, FP, team) {
  down <- 1  # Start from first down
  
  while (down <= 4) {
    if (down < 4) {  # First three downs
      result <- downs_123(D, YTG, FP)  # Get play result
      D <- result[1]
      YTG <- result[2]
      FP <- result[3]
      team <- result[4]  # Check if team possession changes
      
      if (team == 1) {  # Turnover occurred
        down <- 1  # Reset to first down for the other team
#        print("Turnover! Possession switched.")
        break
      } else {
        down <- down + 1  # Move to next down
      }
    } else {  # Fourth down scenario
      play_type <- playChoice(YTG, FP)  # Determine the play type
      
      down_4_result <- down_4(D, YTG, FP, play_type)
      new_state <- down_4_result$state
      flag <- down_4_result$flag
      
      # Update values from down_4 result
      D <- new_state$D
      YTG <- new_state$YTG
      FP <- new_state$FP

      if (flag == 1) {  # If fourth-down play results in a turnover or field goal
        team <- 1  # Switch possession
        down <- 1  # Reset down for new team
#        print("Fourth down play resulted in possession switch.")
        break
      } else {
        down <- 1  # Successful "go for it" means reset to first down
      }
    }
  }
  
#  print(paste("End of play: Down", down, "| Yards to Go:", YTG, "| Field Position:", FP, "| Team:", team))
  return(c(down,YTG,FP,team))
}
```

#### Helper Run_Play
```{r}
yards_gained<- function(FP){
  halfed<-as.integer((100-FP)/2)
  next_field_position<- sample(c("less_than_10","first_half_FP","second_half_FP"),1,prob=c(0.5,0.25,0.25))
  if(next_field_position=="less_than_10"){
    yg<-sample(0:9, 1)
  }
  else if(next_field_position=="first_half_FP")
  {
    yg<-sample(10:halfed,1)
  }
  else{
    yg<-sample(halfed+1:100,1)
  }
  yg
}



downs_123 <- function(D, YTG, FP){
  options <- sample(c("NoTurnover", "Turnover", "Touchdown"), 1, prob = c(0.50, 0.35, 0.15))
  YG <- yards_gained(FP)
  if(options == "NoTurnover"){
    return(c(D + 1, YTG - YG, FP + YG, 0))
  } else if(options == "Turnover"){
    return(c(D, YTG, FP, 1))
  } else {
    return(c(D, YTG, 105, 1))
  }
}



# I made a seperate helping function to decide the play in a fourth down

playChoice <- function(YTG, FP) {
  # Compute the predicted probabilities for each play choice
  probabilities <- predict(mult.model, newdata = data.frame(YTG = YTG, FP = FP), type = "probs")
  
  # Randomly select a play choice based on probabilities
  play_choice <- sample(c("field_goal", "punt", "go_for_it"), size = 1, prob = probabilities)
  
  return(play_choice)
}


# This code simulates the fourth down.

onlyDown4 <- data %>% 
  filter(down==4) %>% 
  rename(YTG=ydstogo,FP=yardline_100) %>% 
  filter(play_type %in% c("field_goal","punt","run"))

mult.model <- multinom(play_type ~ YTG + FP, data = onlyDown4)


## Using Logistic Regression to Predict Field Goal Outcome 
# Get field goal positions from data for relevant plays
field_position <- data %>% filter(field_goal_result %in% c("made", "missed"))
field_position <- field_position$yardline_100
n <- length(field_position)  # Set number of field goals to calculate success from 

my_data <- data.frame(
  field_position = field_position,
  field_goal_success = rbinom(n, 1, prob = 1 / (1 + exp(-(3 - 0.1 * sample(10:60, n, replace = TRUE)))))  # Sigmoid function
)

log.model <- glm(field_goal_success ~ field_position, data = my_data, family = binomial)


## down_4 
# Simulates the 4th down 
# NOTE: Uses logistic regression model (log.model) above
down_4 <- function(D, YTG, FP, play_type, model) {
  # Initialize the flag to indicate whether the epoch function should be triggered
  flag <- 0
  play_type<-playChoice(YTG,FP)
  play_result <- NULL
  
  # Note: For this scenario, we want to call log.model as our model parameter in down_4(). 
  model <- log.model
  
  # Field Goal Scenario
  if (play_type == 'field_goal') {
    # Predict probability of field goal success using log.model 
    prob_success <- predict(model, newdata = data.frame(field_position = FP), type = "response")
    play_result <- ifelse(runif(1) < prob_success, 'made', 'missed')
    
    play_result <- sample(c("made", "missed"), 1)
    if (play_result == 'made') {
      # Successful field goal, set FP to 115 and return to epoch function
      new_state <- list(D = D, YTG = YTG, FP = 115)
      flag <- 1
    } else if (play_result == 'missed') {
      # Missed field goal, possession switches, return to epoch function
      new_state <- list(D = D, YTG = YTG, FP = FP)
      flag <- 1
    }
  }
  
  # Punt Scenario
  else if (play_type == 'punt') {
    play_result <- sample(c("typical", "rare"), 1,prob=c(0.9,0.1))
                          if (play_result == 'typical') {
                            # Typical punt, possession switches to epoch function
                            new_state <- list(D = D, YTG = YTG, FP = FP)
                            flag <- 1
                          } else if (play_result == 'rare') {
                            # Rare scenario (e.g., mishandled punt), stay in drive function and continue
                            new_state <- list(D = D, YTG = YTG, FP = FP)
                            flag <- 0
                          }
  }
  
  # Go for It Scenario
  else if (play_type == 'go_for_it') {
    play_result <- sample(c("successful", "unsuccessful"), 1)
    if (play_result == 'successful') {
      # Successful "go for it" play, stay in the drive with updated first down
      new_state <- list(D = 1, YTG = 10, FP = FP + yards_gained(FP))
      flag <- 0
    } else if (play_result == 'unsuccessful') {
      # Unsuccessful "go for it" play, possession switches, return to epoch function
      new_state <- list(D = D, YTG = YTG, FP = FP)
      flag <- 1
    }
  }
  
  # Return the updated state and flag (0 or 1)
  return(list(state = new_state, flag = flag))
}
```




# Returns Expected Points
```{r}
# Expected points function

simulate_game <- function(down, ytg, fp, n = 10000) {
  results <- numeric(n)
  for (i in 1:n) {
    results[i] <- simulate_epoch(down, ytg, fp)
  }
  mean(results)
}

```



```{r}

set.seed(2000)

start_ranges <- seq(from = 25, to = 70, by = 5)
boundaries<-numeric(0)


for (i in start_ranges){
  success_fp<-i+2
  fail_fp<-100-i
  ES<-simulate_game(1,10,success_fp)
  EF<-simulate_game(1,10,fail_fp)
  p<-EF/(ES+EF)
  boundaries<-c(boundaries,p)
}

boundaries
```


```{r}
### Create kable output 
library(knitr)
library(kableExtra)

# Create matrix to store decision boundaries
decision_boundaries_df <- data.frame(matrix(NA, nrow = 10, ncol = 5))

colnames(decision_boundaries_df) <- c("Yard Range","Quarter1", "Quarter2", "Quarter3", "Quarter4")
# Check these ranges b/c the last group has 6 yards not 5

ranges<-c("25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64","65-69","70-75")

decision_boundaries_df$`Yard Range`<- ranges

ranges<-c(25:29,30:34,35:39,40:44,45:49,50:54,55:59,60:64,65:69,70:74)
yards<-c("25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64","65-69","70-75")

quarter1<-c(0.4949594, 0.4975449, 0.4956879, 0.4992837, 0.4971841, 0.5000513, 0.4992649, 0.5015776, 0.5044593, 0.5050420)
quarter2<-c(0.4951310, 0.4974376, 0.4956930, 0.4992149, 0.4971974, 0.5000000, 0.4993505, 0.5013630, 0.5043730, 0.5047816)
quarter3<-c(0.4950628, 0.4973561, 0.4956416, 0.4993694, 0.4972354, 0.4999829, 0.4993675, 0.5014317, 0.5044923, 0.5050035)
quarter4<-c(0.4953265, 0.4975323, 0.4957096, 0.4992319, 0.4971667, 0.4999102, 0.4994700, 0.5011788, 0.5042107, 0.5047256)

df<-data.frame(yards,quarter1,quarter2,quarter3,quarter4)
colnames(df) <- c("Yard Range", "Q1", "Q2", "Q3", "Q4")

kable(df, caption = "Decision Boundary Probabilites by Quarter and Field Position") %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "hold_position") %>%
  row_spec(0, bold = TRUE) %>%
  kableExtra::add_header_above(c(" " = 5)) %>%
  kableExtra::kable_styling(latex_options = c("striped", "bordered"))
```


